// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBssqpi8MjxsJZpMpecZDajG80mlDYXT3A',
    appId: '1:915809480020:web:99f67a6f579b8dbc5c6cc1',
    messagingSenderId: '915809480020',
    projectId: 'fitmind-7a7ed',
    authDomain: 'fitmind-7a7ed.firebaseapp.com',
    storageBucket: 'fitmind-7a7ed.firebasestorage.app',
    measurementId: 'G-84089QC7D3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5hWX2BpK3Or-R-en9ZI0K30rODGrXGQQ',
    appId: '1:915809480020:ios:3fd3708fc7e2da8c5c6cc1',
    messagingSenderId: '915809480020',
    projectId: 'fitmind-7a7ed',
    storageBucket: 'fitmind-7a7ed.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5hWX2BpK3Or-R-en9ZI0K30rODGrXGQQ',
    appId: '1:915809480020:ios:3fd3708fc7e2da8c5c6cc1',
    messagingSenderId: '915809480020',
    projectId: 'fitmind-7a7ed',
    storageBucket: 'fitmind-7a7ed.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBssqpi8MjxsJZpMpecZDajG80mlDYXT3A',
    appId: '1:915809480020:web:31808ea993011c375c6cc1',
    messagingSenderId: '915809480020',
    projectId: 'fitmind-7a7ed',
    authDomain: 'fitmind-7a7ed.firebaseapp.com',
    storageBucket: 'fitmind-7a7ed.firebasestorage.app',
    measurementId: 'G-5DZ72GGL0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13rxKbKvOy73ThyzXHImzv2TMnBX4zV0',
    appId: '1:915809480020:android:7f9b3a4e19267bbc5c6cc1',
    messagingSenderId: '915809480020',
    projectId: 'fitmind-7a7ed',
    storageBucket: 'fitmind-7a7ed.firebasestorage.app',
  );
}
